export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const SET_VISIBLE_NOTIFICATION = "SET_VISIBLE_NOTIFICATION";
export const SET_DURATION_NOTIFICATION = "SET_DURATION_NOTIFICATION";
export const SET_MESSAGE_NOTIFICATION = "SET_MESSAGE_NOTIFICATION";
export const SET_TYPE_NOTIFICATION = "SET_TYPE_NOTIFICATION";
