const translations = {
  en: {
    login: "Login",
    logout: "Logout",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    birthdate: "Birthdate",
    country: "Country",
    city: "City",
    avatar: "Avatar",
    linkedIn: "LinkedIn",
    gitHub: "GitHub",
    welcome: "Welcome",
    notifications: "Notifications",
    markAsRead: "Mark as read",
    unread: "Unread",
    read: "Read",
    goToRegister: "Sign up",
    goToLogin: "Go to Login",
    loginWithGoogle: "Login with Google",
    loginWithGitHub: "Login with GitHub",
    registerButton: "Create Account",
    resetPassword: "Reset Password",
    resetPasswordButton: "Send Reset Link",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    backToLogin: "Back to Login",
    forgotPassword: "Forgot your password?",

    // Success Messages
    "auth/account-created-success":
      "Your account has been successfully created!",
    "auth/password-reset-success":
      "A password reset email has been sent to your email address.",
    "auth/password-reset-success-check":
      "Check your email for instructions to reset your password.",
    "auth/password-reset-success-confirm":
      "Your password has been successfully updated!",
  },
  es: {
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    register: "Registrarse",
    email: "Correo Electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    firstName: "Nombre",
    lastName: "Apellido",
    phone: "Teléfono",
    birthdate: "Fecha de Nacimiento",
    country: "País",
    city: "Ciudad",
    avatar: "Avatar",
    linkedIn: "LinkedIn",
    gitHub: "GitHub",
    welcome: "Bienvenido",
    notifications: "Notificaciones",
    markAsRead: "Marcar como leído",
    unread: "No leído",
    read: "Leído",
    goToRegister: "Registrarse",
    goToLogin: "Ir al Login",
    loginWithGoogle: "Iniciar con Google",
    loginWithGitHub: "Iniciar con GitHub",
    registerButton: "Crear Cuenta",
    resetPassword: "Restablecer Contraseña",
    resetPasswordButton: "Enviar Enlace de Recuperación",
    newPassword: "Nueva Contraseña",
    confirmNewPassword: "Confirmar Nueva Contraseña",
    backToLogin: "Volver al Login",
    forgotPassword: "¿Olvidaste tu contraseña?",

    // Mensajes de éxito
    "auth/account-created-success": "¡Tu cuenta ha sido creada exitosamente!",
    "auth/password-reset-success":
      "Se ha enviado un correo para restablecer tu contraseña.",
    "auth/password-reset-success-check":
      "Revisa tu correo electrónico para las instrucciones de recuperación.",
    "auth/password-reset-success-confirm":
      "¡Tu contraseña ha sido actualizada correctamente!",
  },
  ca: {
    login: "Iniciar Sessió",
    logout: "Tancar Sessió",
    register: "Registrar-se",
    email: "Correu Electrònic",
    password: "Contrasenya",
    confirmPassword: "Confirma la Contrasenya",
    firstName: "Nom",
    lastName: "Cognom",
    phone: "Telèfon",
    birthdate: "Data de Naixement",
    country: "País",
    city: "Ciutat",
    avatar: "Avatar",
    linkedIn: "LinkedIn",
    gitHub: "GitHub",
    welcome: "Benvingut",
    notifications: "Notificacions",
    markAsRead: "Marcar com a llegit",
    unread: "No llegit",
    read: "Llegit",
    goToRegister: "Registrar-se",
    goToLogin: "Anar al Login",
    loginWithGoogle: "Iniciar amb Google",
    loginWithGitHub: "Iniciar amb GitHub",
    registerButton: "Crear Compte",
    resetPassword: "Restablir Contrasenya",
    resetPasswordButton: "Enviar Enllaç de Recuperació",
    newPassword: "Nova Contrasenya",
    confirmNewPassword: "Confirmar Nova Contrasenya",
    backToLogin: "Tornar al Login",
    forgotPassword: "Has oblidat la teva contrasenya?",

    // Missatges d'èxit
    "auth/account-created-success":
      "El teu compte ha estat creat correctament!",
    "auth/password-reset-success":
      "S'ha enviat un correu per restablir la teva contrasenya.",
    "auth/password-reset-success-check":
      "Revisa el teu correu electrònic per a les instruccions de recuperació.",
    "auth/password-reset-success-confirm":
      "La teva contrasenya s'ha actualitzat correctament!",
  },
};

export default translations;
